//! The three generated artifacts: the report table, the per-case tests, and the baseline.
//!
//! These live in the harness rather than in the bin so that `tests/conformance.rs` can call the
//! SAME functions the bin does. A generator the tests cannot run is a generator whose output the
//! tests can only compare by eye, and `the_report_is_reproducible` and
//! `the_conformance_table_is_current` are exactly the checks that need to run it.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::case::Case;
use super::corpus;
use super::exclusions::Exclusions;
use super::run::{self, Outcome};

/// What a case resolved to. EXCLUDED is decided BEFORE running, so an excluded case is never
/// executed and can never contribute a pass.
pub enum Reported<'a> {
    Excluded(&'a str),
    Ran(Outcome),
}

pub fn outcome_of<'a>(case: &Case, exclusions: &'a Exclusions) -> Reported<'a> {
    match exclusions.reason_for(case) {
        Some(reason) => Reported::Excluded(reason),
        None => Reported::Ran(run::run(case)),
    }
}

/// One file's counts. `pass` is RUNTIME agreement; `static_pass` is a case expecting an error that
/// the checker refused first — agreement too, but a different claim, so never summed into `pass`.
/// A checker refusal that no rule excludes is a `fail`, exactly as an evaluation disagreement is.
#[derive(Clone, Copy, Default)]
pub struct Counts {
    pub pass: usize,
    pub static_pass: usize,
    pub excluded: usize,
    pub fail: usize,
}

impl Counts {
    fn add(&mut self, o: Counts) {
        self.pass += o.pass;
        self.static_pass += o.static_pass;
        self.excluded += o.excluded;
        self.fail += o.fail;
    }
}

pub fn counts(file: &super::case::CaseFile, exclusions: &Exclusions) -> Counts {
    let mut c = Counts::default();
    for case in &file.cases {
        match outcome_of(case, exclusions) {
            Reported::Excluded(_) => c.excluded += 1,
            Reported::Ran(Outcome::Pass) => c.pass += 1,
            Reported::Ran(Outcome::PassStatic(_)) => c.static_pass += 1,
            Reported::Ran(Outcome::Refused(_) | Outcome::Fail(_)) => c.fail += 1,
        }
    }
    c
}

fn total(exclusions: &Exclusions) -> Counts {
    let mut t = Counts::default();
    for file in &corpus().files {
        t.add(counts(file, exclusions));
    }
    t
}

/// One row per corpus file, plus a total and the exclusion breakdown. This is what
/// `conformance/report.md` holds and what the README points at.
pub fn report(exclusions: &Exclusions) -> String {
    let mut out = String::new();
    out.push_str("<!-- @generated by `cargo run -p typed-cel --features conformance --bin conformance-report -- --write` -->\n\n");
    out.push_str("# typed-CEL vs google/cel-spec v0.25.1\n\n");
    out.push_str(
        "Every case is compiled through the checker a policy compiles through, then evaluated. \
         `static` counts the cases that expect an evaluation error and that the checker refused \
         first.\n\n```\n",
    );
    writeln!(
        out,
        "  {:<20} {:>7} {:>7} {:>9} {:>6}",
        "file", "pass", "static", "excluded", "fail"
    )
    .unwrap();

    let mut t = Counts::default();
    for file in &corpus().files {
        let c = counts(file, exclusions);
        writeln!(
            out,
            "  {:<20} {:>7} {:>7} {:>9} {:>6}",
            file.name, c.pass, c.static_pass, c.excluded, c.fail
        )
        .unwrap();
        t.add(c);
    }
    writeln!(
        out,
        "  {:<20} {:>7} {:>7} {:>9} {:>6}",
        "TOTAL", t.pass, t.static_pass, t.excluded, t.fail
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "  Excluded by dialect:").unwrap();
    for (reason, n) in &exclusions.tally(corpus().cases()) {
        writeln!(out, "    {n:>5}  {reason}").unwrap();
    }
    out.push_str("```\n");

    // The FAIL column, broken out. A total is a number; this is the list of things to go and fix,
    // and it is what stops a column of reds from reading as undifferentiated background noise.
    let mut failing: BTreeMap<(&str, &str), usize> = BTreeMap::new();
    for case in corpus().cases() {
        if let Reported::Ran(Outcome::Refused(_) | Outcome::Fail(_)) = outcome_of(case, exclusions)
        {
            *failing
                .entry((case.file.as_str(), case.section.as_str()))
                .or_default() += 1;
        }
    }
    if !failing.is_empty() {
        out.push_str(
            "\n## Failing sections\n\nEvery one of these is a bug in this crate — a case ",
        );
        out.push_str("that fails and is not\nexcluded has no third state to hide in.\n\n```\n");
        for ((file, section), n) in &failing {
            writeln!(out, "  {n:>4}  {file}/{section}").unwrap();
        }
        out.push_str("```\n");
    }
    out
}

/// The markers the README's compatibility block lives between. The block is generated; the prose
/// around it is written by hand, and the splice must not disturb it.
pub const README_BEGIN: &str = "<!-- @generated conformance summary -->";
pub const README_END: &str = "<!-- @end conformance summary -->";

/// The compatibility block the README carries: the headline counts and what the exclusions bought.
///
/// The README does NOT repeat `report.md`'s per-file table. A reader arriving at the README wants
/// one thing — is this CEL? — and that is three numbers plus the list of what the dialect declined
/// to implement. The per-file breakdown and the failing sections are triage, and they stay in
/// `report.md` where the person doing the triage is already looking.
pub fn readme_summary(exclusions: &Exclusions) -> String {
    let t = total(exclusions);
    let mut out = String::new();
    out.push_str("```text\n");
    writeln!(
        out,
        "  google/cel-spec v0.25.1 — {} cases, each checked, then evaluated\n",
        corpus().len()
    )
    .unwrap();
    writeln!(out, "    {:>5}  pass", t.pass).unwrap();
    writeln!(
        out,
        "    {:>5}  pass statically (the case expects an error; the checker refused it first)",
        t.static_pass
    )
    .unwrap();
    writeln!(out, "    {:>5}  excluded by dialect", t.excluded).unwrap();
    writeln!(out, "    {:>5}  fail\n", t.fail).unwrap();
    writeln!(out, "  Excluded by dialect:").unwrap();
    for (reason, n) in &exclusions.tally(corpus().cases()) {
        writeln!(out, "    {n:>5}  {reason}").unwrap();
    }
    out.push_str("```\n");
    out
}

/// `readme` with its compatibility block replaced by a live one.
///
/// Returns the whole document rather than the block so the caller can compare or write it whole:
/// `the_conformance_summary_is_current` asserts this is the identity function on the committed
/// README, which is the same check as "regenerate and diff" without a temporary file.
pub fn readme_with_summary(readme: &str, exclusions: &Exclusions) -> Result<String, String> {
    let begin = readme
        .find(README_BEGIN)
        .ok_or_else(|| format!("README.md has no `{README_BEGIN}` marker"))?
        + README_BEGIN.len();
    let end = readme
        .find(README_END)
        .ok_or_else(|| format!("README.md has no `{README_END}` marker"))?;
    if end < begin {
        return Err("README.md's conformance markers are in the wrong order".into());
    }
    Ok(format!(
        "{}\n\n{}\n{}",
        &readme[..begin],
        readme_summary(exclusions),
        &readme[end..]
    ))
}

/// The identifier a case's generated test gets. Exposed because
/// `every_case_resolves_to_exactly_one_outcome` re-derives the expected set from the corpus and
/// compares it to what is actually in `gen/cases.rs`.
pub fn test_names(exclusions: &Exclusions) -> Vec<String> {
    let mut used: BTreeMap<String, usize> = BTreeMap::new();
    let mut out = Vec::new();
    for case in corpus().cases() {
        if exclusions.reason_for(case).is_some() {
            continue;
        }
        let mut name = sanitize(&case.unique_id());
        // `sanitize` is not injective (`a-b` and `a_b` collide), so uniqueness is enforced rather
        // than assumed. Two cases sharing a generated name would mean one silently replaced the
        // other and the corpus quietly got smaller.
        let slot = used.entry(name.clone()).or_default();
        if *slot > 0 {
            name = format!("{name}__{}", *slot + 1);
        }
        *slot += 1;
        out.push(name);
    }
    out
}

/// One `#[test]` per NON-excluded case.
///
/// An excluded case gets no test at all — deliberately. A test that exists and passes vacuously is
/// the shape this harness was built to avoid; exclusions are accounted for in the report and in
/// `every_case_resolves_to_exactly_one_outcome`, where they cannot be mistaken for a pass.
pub fn cases_rs(exclusions: &Exclusions) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p typed-cel --features conformance --bin \
         conformance-report -- --write`\n\
         //\n\
         // One test per NON-EXCLUDED google/cel-spec case. Do not edit by hand: regenerate.\n\
         // A test that passes BY panicking must never appear here — the harness has three\n\
         // outcomes and \"passes by failing\" is not among them. `no_should_panic_anywhere`\n\
         // greps this file for the attribute, which is why it is not spelled out.\n\n",
    );
    let names = test_names(exclusions);
    let runnable = corpus()
        .cases()
        .filter(|c| exclusions.reason_for(c).is_none());
    for (name, case) in names.iter().zip(runnable) {
        writeln!(out, "#[test]").unwrap();
        writeln!(out, "fn {name}() {{").unwrap();
        writeln!(
            out,
            "    super::check({:?}, {:?}, {:?}, {});",
            case.file, case.section, case.name, case.ordinal
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
    }
    out
}

/// A corpus id as a Rust identifier.
fn sanitize(id: &str) -> String {
    let mut s: String = id
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s.to_lowercase()
}

/// The committed counts, per file. A case moving PASS -> FAIL is a red; a case moving FAIL -> PASS
/// requires updating this file, so an improvement is NOTICED rather than absorbed into a slightly
/// nicer number nobody re-reads.
pub fn baseline_toml(exclusions: &Exclusions) -> String {
    let mut out = String::new();
    out.push_str(
        "# @generated by `cargo run -p typed-cel --features conformance --bin \
         conformance-report -- --write`\n\
         #\n\
         # Per-file conformance counts against google/cel-spec v0.25.1. `the_baseline_holds`\n\
         # compares a live run to this file and fails on ANY difference, in either direction.\n\n",
    );
    for file in &corpus().files {
        let c = counts(file, exclusions);
        writeln!(out, "[{}]", file.name).unwrap();
        writeln!(out, "pass = {}", c.pass).unwrap();
        writeln!(out, "static_pass = {}", c.static_pass).unwrap();
        writeln!(out, "excluded = {}", c.excluded).unwrap();
        writeln!(out, "fail = {}", c.fail).unwrap();
        writeln!(out).unwrap();
    }
    out
}
